### ISSUE TITLE
Add support for HTTPS Resource Records

### ISSUE THREAD

**Issue by Vloeck** [Valodim/terraform-provider-desec#15]
When I want to create a resource record with type "HTTPS", I get the following error message:
` Error: expected type to be one of [A AAAA CAA CNAME TXT SRV LOC MX NS SPF CERT DNSKEY DS NAPTR SMIMEA SSHFP TLSA URI PTR], got HTTPS`

~~Can you implement this?~~
Can you merge this and possibly release a new version?

**Comment by Valodim** [comment]
done :)
